const STEPS = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CLAIM_ACCOUNT: 'CLAIM_ACCOUNT',
}

export default STEPS
